name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: cli2rest:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker image
        run: |
          docker run --name cli2rest-test -d -p 8000:8000 cli2rest:test
          sleep 5  # Wait for container to start
          curl -s http://localhost:8000/health | grep '"status":"healthy"'
          docker stop cli2rest-test
          
      - name: Check registry access
        if: github.event_name != 'pull_request'
        run: |
          echo "This step would push to the registry in the docker-publish workflow"
